//! The app that walks around in the terrain.
//!
//! The terrain itself is generated by the engine-free `world` crate, which
//! [`terrain`] re-exports wholesale so the rest of the app has one place to
//! import terrain things from. This crate is a library under a thin `game`
//! binary, so that the app's own parts — the camera, the menu, the command
//! line — are reachable from tests rather than sealed inside a `main`.

pub mod ambience;
pub mod bindings;
pub mod boat;
pub mod camera;
pub mod capture;
pub mod cli;
pub mod compass;
pub mod debug;
pub mod menu;
pub mod net;
pub mod terrain;

#[cfg(test)]
mod testing;

use bevy::prelude::*;

/// Colour of the sky above the horizon. The camera's distance fog fades to the
/// same colour, so the two meet seamlessly.
pub const SKY: Color = Color::srgb(0.63, 0.80, 0.93);

/// Distance from the eye at which aerial haze starts to take the ground over,
/// in metres.
pub const HAZE_START: f32 = 320.0;
/// Distance at which the haze has fully replaced the ground with [`SKY`]. This
/// is the edge of what the camera can see at all, whatever it is pointed at, so
/// anything the picture depends on has to reach at least this far — the sun's
/// shadows included.
pub const HAZE_END: f32 = 900.0;

/// Size of the window the game is played in, in pixels. Captured shots are
/// sized by `--resolution` instead, having no window to take it from.
pub const WINDOW: UVec2 = UVec2::new(1280, 720);

/// A surface in `base_color` with nothing polished about it.
///
/// Everything the game draws is lit this way — ground, water, hulls, the
/// markers other players stand as. A specular highlight is a gradient across
/// a facet, and a gradient is the one thing a look built out of flat tones
/// cannot have: it would read as the facet being curved, which is exactly
/// what the shading says it is not.
///
/// A surface wanting one thing about it different spreads the rest of this
/// over its own: `StandardMaterial { alpha_mode, ..matte(colour) }`.
pub fn matte(base_color: Color) -> StandardMaterial {
    StandardMaterial {
        base_color,
        perceptual_roughness: 1.0,
        metallic: 0.0,
        reflectance: 0.0,
        ..default()
    }
}

/// How far of the way to a target an exponential ease travels in `dt`
/// seconds, as a fraction to interpolate by: `value.lerp(target, eased(..))`.
///
/// `rate` is how fast the gap closes, in e-foldings per second — its
/// reciprocal is the time constant, so most of any change arrives within
/// `1/rate` seconds and it is all but done in three times that.
///
/// The exponential is what makes the ease frame-rate independent. Taking a
/// fixed fraction of the gap each frame would close it at whatever speed the
/// machine happened to render at; this is the exact solution over the frame's
/// own length, so the same movement takes the same time everywhere.
///
/// Note that this never quite arrives — it only ever closes a fraction of
/// what is left. Anything that has to *stop* needs a threshold of its own to
/// snap the tail, as the boat's way does.
pub fn eased(rate: f32, dt: f32) -> f32 {
    1.0 - (-rate * dt).exp()
}

/// Top-level screen the app is on.
#[derive(States, Debug, Clone, Copy, Default, PartialEq, Eq, Hash)]
pub enum AppState {
    #[default]
    MainMenu,
    /// Choosing the seed of the world about to be entered, and whether to
    /// share it with anyone else.
    NewWorld,
    /// Naming a server to play in.
    JoinWorld,
    /// Choosing which key does what.
    Settings,
    InWorld,
}
